spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/todos
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
